#!/bin/sh
echo 'foooo2';
# Editing this file in certain IDEs will break the hard link.
# To change this file without breaking the hard link edit it in Notepad.
# Run the installation script associated with this file to create a new hard link.

protected_branch='master'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
working_dir='../'
exe_bin='node_modules/.bin'

if [ $current_branch = $protected_branch ]
then
    exit 0
fi

echo "Starting Pre-Commit Check on branch: $current_branch"
echo "Changing directory to $working_dir..."

cd $working_dir
echo "Done"

PRETTIER_ELAPSED_TIME=0
PRETTIER_EXIT_CODE=0
staged_prettier_files=$(git diff --staged --relative=$working_dir --name-only --diff-filter=d | grep -E '.html|scss|ts$')

if [ "$staged_prettier_files" != "" ]
then
    echo "Running Prettier..."
    PRETTIER_START_TIME=$SECONDS

    $exe_bin/prettier --write $staged_prettier_files

    if [ $? -ne 0 ]
    then
        PRETTIER_EXIT_CODE=1
    else
        echo "Passed Prettier!"
    fi

    PRETTIER_ELAPSED_TIME=$(($SECONDS - $PRETTIER_START_TIME))
    echo "Prettier done in ${PRETTIER_ELAPSED_TIME}s"
fi

STYLELINT_ELAPSED_TIME=0
STYLELINT_EXIT_CODE=0
staged_scss_files=$(git diff --staged --relative=$working_dir --name-only --diff-filter=d | grep -E '.scss$')

if [ "$staged_scss_files" != "" ]
then
    echo "Running Stylelint..."
    STYLELINT_START_TIME=$SECONDS

    $exe_bin/stylelint $staged_scss_files --quiet scss

    if [ $? -ne 0 ]
    then
        STYLELINT_EXIT_CODE=1
    else
        echo "Passed Stylelint!"
    fi

    STYLELINT_ELAPSED_TIME=$(($SECONDS - $STYLELINT_START_TIME))
    echo "Stylelint done in ${STYLELINT_ELAPSED_TIME}s"
fi

ESLINT_ELAPSED_TIME=0
ESLINT_EXIT_CODE=0
staged_ts_files=$(git diff --staged --relative=$working_dir --name-only --diff-filter=d | grep -E '.ts$')

if [ "$staged_ts_files" != "" ]
then
    echo "Running ESLint..."
    ESLINT_START_TIME=$SECONDS

    $exe_bin/eslint $staged_ts_files --fix

    if [ $? -ne 0 ]
    then
        ESLINT_EXIT_CODE=1
    else
        echo "Passed ESLint!"
    fi

    ESLINT_ELAPSED_TIME=$(($SECONDS - $ESLINT_START_TIME))
    echo "ESLint done in ${ESLINT_ELAPSED_TIME}s"
fi


TOTAL_ELAPSED_TIME=$(($PRETTIER_ELAPSED_TIME + $STYLELINT_ELAPSED_TIME + $ESLINT_ELAPSED_TIME))
echo "Done in ${TOTAL_ELAPSED_TIME}s"

if [ $PRETTIER_EXIT_CODE -ne 0 ] || [ $STYLELINT_EXIT_CODE -ne 0 ] || [ $ESLINT_EXIT_CODE -ne 0 ]
then
    exit 1
fi

git add $staged_prettier_files $staged_ts_files